### ISSUE TITLE
Crash when deleting folder

### ISSUE THREAD

**Issue by Srekel** [jlaumon/AssetCooker#11]
I removed a folder containing a bunch of these splatmap pngs, this caused asset cooker to crash. 

![image](https://github.com/user-attachments/assets/ebb9228a-9feb-42b1-abbd-98c18e41d74c)

There shouldn't be any rules processing these files so likely not related to that.

**Comment by jlaumon** [comment]
Thanks for the report!

I'm doing something arguably stupid where I check for error codes I know and force a crash if it's one I don't know. And it looks like you found a way to make it fail to open a file with 0x00000002, which is `ERROR_FILE_NOT_FOUND`.

https://github.com/jlaumon/AssetCooker/blob/50492b344a7c0a6d884eb696d0467ce350576f49/src/FileSystem.cpp#L565-L576
