### ISSUE TITLE
`sParseMakeDepFile` fails on glslc/glslang dep files

### ISSUE THREAD

**Issue by Eiyeron** [jlaumon/AssetCooker#3]
Hello.

I'm currently trying to replace a part of my shader workflow to see how helpful AssetCooker would be (compared to CMake generated solutions failing to notice changes in dependencies files) and i noticed that trying to use the `Make` format but it fails with the depfile generated by `glsc` as it fails to split the dependency list.

From what I understand, looks like `sParseMakeDepFile` is trying to split the input file by lines where as glslc generates the input list as a list of files separated by white spaces, according to the [documentation](https://github.com/google/shaderc/tree/main/glslc#dependency-generation-options)

Here a sample coming directly from one of my failing files

```make
D:\Dev\Cpp\Engine\shaders\basic_prepass.vert.spv: D:\Dev\Cpp\Engine\shaders\basic_prepass.vert.glsl D:\Dev\Cpp\Engine\shaders/shards/view_descriptor_set.glsl
```

Assuming that the input files provided are split by line returns will provoke failing behavior starting from `gGetAbsolutePath` where sometimes the process will silently fail and sometimes just crash.

I can't promise anything but I might look later for a "fix" for that, depending on my availability.

Have a nice day.

A sidenote: I don't know if it's worth making a whole issue/PR for that but the README is currently slightly wrong in the main branch as of f4f0cbfe: the expected structure format for `depfile` variable is a table named `DepFile` with `Path` and `Format`, not two different variables.

**Comment by jlaumon** [comment]
Thanks for both reports.

Yeah I knew that parsing function was lame, I also need to check what happens if the files have spaces in them.

PR welcome but otherwise I'll take a look a fixing both things when I've recovered from Game Camp 😂
